language: go
go:
  - 1.9.x
  - 1.10.x
  - master

matrix:
 fast_finish: true
 allow_failures:
   - go: master

sudo: false

script:
 - go get -d -t -v ./...
 - go install -v $TAGS ./...
 - ./.ci/code-coverage.sh

after_success:
 - bash <(curl -s https://codecov.io/bash)
